# Generated by Django 5.1.3 on 2024-12-01 16:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('general_cleaning', 'Общий клининг'), ('deep_cleaning', 'Генеральная уборка'), ('post_construction_cleaning', 'Послестроительная уборка'), ('dry_cleaning', 'Химчистка')], max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=255)),
                ('contact_info', models.CharField(max_length=255)),
                ('preferred_date_time', models.DateTimeField()),
                ('payment_type', models.CharField(choices=[('cash', 'Наличные'), ('card', 'Банковская карта')], max_length=10)),
                ('status', models.CharField(choices=[('new', 'Новая заявка'), ('in_progress', 'В работе'), ('completed', 'Выполнено'), ('canceled', 'Отменено')], default='new', max_length=20)),
                ('cancellation_reason', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cleaning.service')),
            ],
        ),
    ]
