# Generated by Django 5.1.3 on 2024-12-05 19:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cleaning', '0002_add_services'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='request',
            options={'verbose_name': 'Заявка', 'verbose_name_plural': 'Заявки'},
        ),
        migrations.AlterModelOptions(
            name='service',
            options={'verbose_name': 'Услуга', 'verbose_name_plural': 'Услуги'},
        ),
        migrations.AlterField(
            model_name='request',
            name='address',
            field=models.CharField(max_length=255, verbose_name='Адрес'),
        ),
        migrations.AlterField(
            model_name='request',
            name='cancellation_reason',
            field=models.TextField(blank=True, null=True, verbose_name='Причина отмены'),
        ),
        migrations.AlterField(
            model_name='request',
            name='contact_info',
            field=models.CharField(max_length=255, verbose_name='Контактная информация'),
        ),
        migrations.AlterField(
            model_name='request',
            name='payment_type',
            field=models.CharField(choices=[('cash', 'Наличные'), ('card', 'Банковская карта')], max_length=10, verbose_name='Тип оплаты'),
        ),
        migrations.AlterField(
            model_name='request',
            name='preferred_date_time',
            field=models.DateTimeField(verbose_name='Дата и время'),
        ),
        migrations.AlterField(
            model_name='request',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cleaning.service', verbose_name='Услуга'),
        ),
        migrations.AlterField(
            model_name='request',
            name='status',
            field=models.CharField(choices=[('new', 'Новая заявка'), ('in_progress', 'В работе'), ('completed', 'Выполнено'), ('canceled', 'Отменено')], default='new', max_length=20, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='request',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='service',
            name='name',
            field=models.CharField(choices=[('general_cleaning', 'Общий клининг'), ('deep_cleaning', 'Генеральная уборка'), ('post_construction_cleaning', 'Послестроительная уборка'), ('dry_cleaning', 'Химчистка')], max_length=50, unique=True, verbose_name='Название услуги'),
        ),
    ]
